### ISSUE TITLE
Can this container code preform a xcodebuild test?  (deploy app to real iOS device then start in test mode)

### ISSUE THREAD

**Issue by aaronmagi** [mstorsjo/xcode-cross#1]
I wanted to know with your container version can you use xcbuild to do a "test". IE build a particular xcode project and then preform the build then test which installs and runs the app on the real iOS device?

Thank you I thought I would ask prior to going through the setup.

**Comment by mstorsjo** [comment]
Answered in https://github.com/facebook/xcbuild/issues/37#issuecomment-466548079.
