### ISSUE TITLE
Can  use it compile MacOS target?

### ISSUE THREAD

**Issue by zuowanbushiwo** [mstorsjo/xcode-cross#7]
Thank you very much for this good project</br>
 I see the content of the setup-toolchain.sh file seems to support macos, is that right? Is there any difference between this 
project https://github.com/tpoechtrager/osxcross ？</br> 
 thanks!  
 best regards

**Comment by mstorsjo** [comment]
It's essentially the same as that project, yes, just with a slightly different way of setting it up, and combining with the xcbuild project (which allows building some xcodeproject files).

**Comment by mstorsjo** [comment]
And yes, this project can compile things both for iOS and macOS, and other targets supported by xcode.

**Comment by zuowanbushiwo** [comment]
Thank you very much, you are really so friendly, so quick and direct reply to me. 

I have never been in contact with ios and macos before, but someone left recently and I need to accept this job. The  main  
purpose is to compile a digital signal processing algorithm library based on C++ without any dependencies. They used to 
compile on various platforms, compiling ios and macOS libraries on Mac, compiling win32 libraries on windows, and compiling
 linux and Android  Library on linux., I think this is too much trouble, I need to manage multiple computers. So I want to cross-compile, compile library files of various platforms and architectures on ubuntu, and find that it is feasible through searching in
 the last two days (especially when I found your project).   <br/>
     1. The xcode.tar.xz your readme mentioned, is Xcode_7.2.1.dmg or Xcode_10.1.xip (https://pan.macxin.com/Software/Xcode/) they obtained it? Decompress first and then get xcode.tar.xz through your strip-xcode.sh ?   <br/>  
   2. https://github.com/apple-cross-toolchain/apple-sdks/releases
is  the apple-sdks-xcode-XX.XX.tar.xz in this page  available ？ Can it be used in your project? If so, compare the above, is this after trip-xcode?   <br/>  
    3. Our project is compiled based on cmake, have you found a suitable cmake toolchain.cmake, can this https://github.com/leetal/ios-cmake/blob/master/ios.toolchain.cmake work?   <br/>
     Looking forward to your reply 。
     thanks！
     best regards

**Comment by mstorsjo** [comment]
> 1. The xcode.tar.xz your readme mentioned, is Xcode_7.2.1.dmg or Xcode_10.1.xip (https://pan.macxin.com/Software/Xcode/) they obtained it? Decompress first and then get xcode.tar.xz through your strip-xcode.sh ? 

You need to unpack the official xcode packages yes, then run my script on it to remove the things this doesn't need. My tools don't work with the original dmg/xip packages.

> 2. https://github.com/apple-cross-toolchain/apple-sdks/releases
> is the apple-sdks-xcode-XX.XX.tar.xz in this page available ？ Can it be used in your project? If so, compare the above, is this after trip-xcode? 

It might be possible to make things work with those toolchains too, but I haven't investigated that. It was my understanding that it's not legal to redistribute those files like that.

> 3. Our project is compiled based on cmake, have you found a suitable cmake toolchain.cmake, can this https://github.com/leetal/ios-cmake/blob/master/ios.toolchain.cmake work? 

I haven't really built anything with cmake with this toolchain... Overall that cmake toolchain file looks incredibly complex; it's possible to do things with much much less setup too by just setting the cross compiler names. I don't have any example offhand, but @alexandre-janniaux might have one (if he happens to have a copy of vlc/contrib/<build>/toolchain.cmake for these targets).

**Comment by zuowanbushiwo** [comment]
@mstorsjo  
Thanks！
1. I extracted Xcode.app from Xcode_10.1.xip through https://github.com/tpoechtrager/osxcross/blob/master/tools/gen_sdk_package_pbzx.sh this script, then cut it through strip-
xcode.sh, and finally docker build success.</br>
2. https://github.com/apple-cross-toolchain/apple-sdks/releases The above apple-sdks-xcode-XX.XX.tar.xz lacks the 
Contents/Developer/usr/bin directory which causes docker build to fail .</br>
At present, the configuration of cmake's toolchain needs to be studied.

**Comment by mstorsjo** [comment]
> 2. https://github.com/apple-cross-toolchain/apple-sdks/releases The above apple-sdks-xcode-XX.XX.tar.xz lacks the
>    Contents/Developer/usr/bin directory which causes docker build to fail .

Yes, those won't work as-is with the build scripts I have right now. It's probably quite possible to make the scripts work with those directories, for just calling the plain compiler (like `arm64-apple-darwin-clang -miphoneos-version-min=9.0 -isysroot /path/to/sysroot`) but it won't be enough for the xcbuild parts.

If it's easy to do practically, I wouldn't mind modifications to these scripts so they work with both actual stripped xcode bundles and those sdks from github.

**Comment by zuowanbushiwo** [comment]
@mstorsjo 
What's wrong with this?
![image](https://user-images.githubusercontent.com/3354428/130199934-e0a6123d-6fb8-4efe-b229-0849bb67d015.png)


toolchain.cmake
[ios.toolchain.txt](https://github.com/mstorsjo/xcode-cross/files/7019986/ios.toolchain.txt)

thanks！
best regards

**Comment by mstorsjo** [comment]
You can't pass a compiler + flags via the `CMAKE_CXX_COMPILER` variable, that needs to be the name of the compiler executable/wrapper itself, nothing else. If you pass it like `CXX="...clang++ -flag1 -flag2" cmake ..` I think you can pass both at the same time, or pass them separately as `CMAKE_CXX_COMPILER="<triple>-clang++" CMAKE_CXX_FLAGS="-flag1 -flag2"`. (In some cases you might need to pass them via `CMAKE_CXX_FLAGS_INIT` instead of plain `CMAKE_CXX_FLAGS`, but I think the regular form of the variable might work here.)

**Comment by zuowanbushiwo** [comment]
@mstorsjo 
![image](https://user-images.githubusercontent.com/3354428/130203736-267b011c-81ff-47f8-9985-fd12a899d0d8.png)

but  I can compile successfully with a single command:
       /opt/xcode-cross/bin/apple-darwin-clang++  -arch armv7 -isysroot /opt/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk  -o test hello-world.cpp

and file：
      test: Mach-O armv7 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE>

Thanks!

**Comment by mstorsjo** [comment]
> @mstorsjo
> ![image](https://user-images.githubusercontent.com/3354428/130203736-267b011c-81ff-47f8-9985-fd12a899d0d8.png)
> 
> but I can compile successfully with a single command:
> /opt/xcode-cross/bin/apple-darwin-clang++ -arch armv7 -isysroot /opt/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -o test hello-world.cpp
> 
> and file：
> test: Mach-O armv7 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE>

It looks like something, somewhere, is setting flags for targeting a too low OS version (5.0.0), try adding `-miphoneos-version-min=9.0` or something, among your compiler flags. You often get strange errors like that if you try to target version way under what the SDK supports targeting.

**Comment by zuowanbushiwo** [comment]
@mstorsjo 
     I compiled successfully ！！

           hello-world: Mach-O armv7 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE>

 you are awesome and  friendly ！ thanks！

**Comment by zuowanbushiwo** [comment]
Hi  mstorsjo
     I use the following cmake configuration：
        [ios.toolchain.txt](https://github.com/mstorsjo/xcode-cross/files/7020536/ios.toolchain.txt)

 build   [c_helloworld](https://github.com/dev-cafe/cmake-cookbook/tree/master/chapter-01/recipe-01/c-example) and   [cxx_helloworld](https://github.com/dev-cafe/cmake-cookbook/tree/master/chapter-01/recipe-01/cxx-example)  in os (ios armv7)，os64(ios arm64), tvos( tvos arm64) and mac (macosx  x86_64)  all build successful.

thanks！
best regards
