### ISSUE TITLE
Does the compiler_rt function support?

### ISSUE THREAD

**Issue by zuowanbushiwo** [mstorsjo/xcode-cross#8]
I noticed that the build process of dockerfile doesn't seem to be supported by compiler-rt. Is that true?

Thanks！
Best  Regards

**Comment by mstorsjo** [comment]
I do not understand what you mean with your question. The xcode bundle does contain files from compiler-rt, like /opt/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.1/lib/darwin/libclang_rt.ios.a, and they are hooked up and used automatically by clang.

**Comment by zuowanbushiwo** [comment]
@mstorsjo 
thanks!   I view a MacOS cross-build [dockerfile](https://github.com/nephatrine/docker-nxbuilder/blob/darwin/Dockerfile#L51) based on osxcross, which is through [build_compiler_rt.sh,](https://github.com/tpoechtrager/osxcross/blob/master/build_compiler_rt.sh) then cpoy some libclang_rt*.a, libclang_rt*.dylib to clang lib directory, so CXX_FLAGS(C_FLAGS)  can soupprt  -rtlib=compiler-rt  feature.
But through your comments above, I have understood.  Your implementation is more concise.  :+1:  :thumbsup:

best regards
